package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Components generated by hbm2java
 */
public class Components  implements java.io.Serializable {


     private Long coId;
     private String coName;
     private Long coQuantity;
     private String coManufacturer;
     private Date coDate;
     private Set coops = new HashSet(0);

    public Components() {
    }

	
    public Components(Long coId) {
        this.coId = coId;
    }
    public Components(Long coId, String coName, Long coQuantity, String coManufacturer, Date coDate, Set coops) {
       this.coId = coId;
       this.coName = coName;
       this.coQuantity = coQuantity;
       this.coManufacturer = coManufacturer;
       this.coDate = coDate;
       this.coops = coops;
    }
   
    public Long getCoId() {
        return this.coId;
    }
    
    public void setCoId(Long coId) {
        this.coId = coId;
    }
    public String getCoName() {
        return this.coName;
    }
    
    public void setCoName(String coName) {
        this.coName = coName;
    }
    public Long getCoQuantity() {
        return this.coQuantity;
    }
    
    public void setCoQuantity(Long coQuantity) {
        this.coQuantity = coQuantity;
    }
    public String getCoManufacturer() {
        return this.coManufacturer;
    }
    
    public void setCoManufacturer(String coManufacturer) {
        this.coManufacturer = coManufacturer;
    }
    public Date getCoDate() {
        return this.coDate;
    }
    
    public void setCoDate(Date coDate) {
        this.coDate = coDate;
    }
    public Set getCoops() {
        return this.coops;
    }
    
    public void setCoops(Set coops) {
        this.coops = coops;
    }

    public void trimStrings(){
       if (coName != null) coName = coName.trim();
       if (coManufacturer != null) coManufacturer = coManufacturer.trim();
    }

    public void cutNulls(){
       if (coName == null) coName = "-";
       if (coManufacturer == null) coManufacturer = "-";
       if (coDate == null) coDate = new Date();
       if (coQuantity == null) coQuantity = new Long(0);
    }

}


