package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA


/**
 * Coop generated by hbm2java
 */
public class Coop  implements java.io.Serializable {


     private Long coopId;
     private Operations operations;
     private Components components;
     private Long coopQuantity;

    public Coop() {
    }

    public Coop(Operations operations, Components components, Long coopQuantity) {
       this.operations = operations;
       this.components = components;
       this.coopQuantity = coopQuantity;
    }
   
    public Long getCoopId() {
        return this.coopId;
    }
    
    public void setCoopId(Long coopId) {
        this.coopId = coopId;
    }
    public Operations getOperations() {
        return this.operations;
    }
    
    public void setOperations(Operations operations) {
        this.operations = operations;
    }
    public Components getComponents() {
        return this.components;
    }
    
    public void setComponents(Components components) {
        this.components = components;
    }
    public Long getCoopQuantity() {
        return this.coopQuantity;
    }
    
    public void setCoopQuantity(Long coopQuantity) {
        this.coopQuantity = coopQuantity;
    }




}


