package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private Long doId;
     private String doName;
     private String doUrl;
     private Set doops = new HashSet(0);

    public Documents() {
    }

	
    public Documents(Long doId) {
        this.doId = doId;
    }
    public Documents(Long doId, String doName, String doUrl, Set doops) {
       this.doId = doId;
       this.doName = doName;
       this.doUrl = doUrl;
       this.doops = doops;
    }
   
    public Long getDoId() {
        return this.doId;
    }
    
    public void setDoId(Long doId) {
        this.doId = doId;
    }
    public String getDoName() {
        return this.doName;
    }
    
    public void setDoName(String doName) {
        this.doName = doName;
    }
    public String getDoUrl() {
        return this.doUrl;
    }
    
    public void setDoUrl(String doUrl) {
        this.doUrl = doUrl;
    }
    public Set getDoops() {
        return this.doops;
    }
    
    public void setDoops(Set doops) {
        this.doops = doops;
    }

    public void trimStrings(){
       if (doName != null) doName = doName.trim();
       if (doUrl != null) doUrl = doUrl.trim();
    }

    public void cutNulls(){
       if (doName == null) doName = "-";
       if (doUrl == null) doUrl = "-";
    }

}


