package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA


/**
 * Equipment generated by hbm2java
 */
public class Equipment  implements java.io.Serializable {


     private Long eqId;
     private Operations operations;
     private String eqManufacturer;
     private String eqComment;
     private String eqName;

    public Equipment() {
    }

	
    public Equipment(Long eqId) {
        this.eqId = eqId;
    }
    public Equipment(Long eqId, Operations operations, String eqManufacturer, String eqComment, String eqName) {
       this.eqId = eqId;
       this.operations = operations;
       this.eqManufacturer = eqManufacturer;
       this.eqComment = eqComment;
       this.eqName = eqName;
    }
   
    public Long getEqId() {
        return this.eqId;
    }
    
    public void setEqId(Long eqId) {
        this.eqId = eqId;
    }
    public Operations getOperations() {
        return this.operations;
    }
    
    public void setOperations(Operations operations) {
        this.operations = operations;
    }
    public String getEqManufacturer() {
        return this.eqManufacturer;
    }
    
    public void setEqManufacturer(String eqManufacturer) {
        this.eqManufacturer = eqManufacturer;
    }
    public String getEqComment() {
        return this.eqComment;
    }

    public void setEqComment(String eqComment) {
        this.eqComment = eqComment;
    }

    public String getEqName() {
        return this.eqName;
    }

    public void setEqName(String eqName) {
        this.eqName = eqName;
    }

    public void trimStrings(){
       if (eqManufacturer != null) eqManufacturer = eqManufacturer.trim();
       if (eqComment != null) eqComment = eqComment.trim();
       if (eqName != null) eqName = eqName.trim();
    }

    public void cutNulls(){
       if (eqManufacturer == null) eqManufacturer = "-";
       if (eqComment == null) eqComment = "-";
       if (eqName == null) eqName = "-";
    }

}


