package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA

/**
 * Log generated by hbm2java
 */

import com.mikevostrikov.ralter.app.domain.model.workers.Employee;
import java.sql.Timestamp;

public class Log  implements java.io.Serializable {


     private Long loId;
     private Employee employee;
     private Operations operations;
     private Products products;
     private Timestamp loTimedate;
     private String loComment;
     private String loErr;

    public Log() {
    }

	
    public Log(Long loId) {
        this.loId = loId;
    }
    public Log(Long loId, Employee employees, Operations operations, Products products, Timestamp loTimedate, String loComment, String loErr) {
       this.loId = loId;
       this.employee = employees;
       this.operations = operations;
       this.products = products;
       this.loTimedate = loTimedate;
       this.loComment = loComment;
       this.loErr = loErr;
    }
   
    public Long getLoId() {
        return this.loId;
    }
    
    public void setLoId(Long loId) {
        this.loId = loId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employees) {
        this.employee = employees;
    }
    public Operations getOperations() {
        return this.operations;
    }
    
    public void setOperations(Operations operations) {
        this.operations = operations;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Timestamp getLoTimedate() {
        return this.loTimedate;
    }
    
    public void setLoTimedate(Timestamp loTimedate) {
        this.loTimedate = loTimedate;
    }
    public String getLoComment() {
        return this.loComment;
    }
    
    public void setLoComment(String loComment) {
        this.loComment = loComment;
    }
    public String getLoErr() {
        return this.loErr;
    }
    
    public void setLoErr(String loErr) {
        this.loErr = loErr;
    }




}


