package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Operations generated by hbm2java
 */
public class Operations  implements java.io.Serializable {


     private Long opId;
     private String opName;
     private String opDescription;
     private Double opDuration;
     private String opComplexity;
     private String opComment;
     private Operations nextOperation = null;
     private Set prevOperation = new HashSet(0);
     private Set suops = new HashSet(0);
     private Set logs = new HashSet(0);
     private Set doops = new HashSet(0);
     private Set equipments = new HashSet(0);
     private Set coops = new HashSet(0);

    public Operations() {
    }

	
    public Operations(Long opId) {
        this.opId = opId;
    }
    public Operations(Long opId, Operations nextOperation, Set prevOperation, String opName, String opDescription, Double opDuration, String opComplexity, String opComment, String opOpId, Set suops, Set logs, Set operationses, Set doops, Set equipments, Set coops) {
       this.opId = opId;
       this.nextOperation = nextOperation;
       this.prevOperation = prevOperation;
       this.opName = opName;
       this.opDescription = opDescription;
       this.opDuration = opDuration;
       this.opComplexity = opComplexity;
       this.opComment = opComment;
       this.suops = suops;
       this.logs = logs;
       this.doops = doops;
       this.equipments = equipments;
       this.coops = coops;
    }
   
    public Long getOpId() {
        return this.opId;
    }
    
    public void setOpId(Long opId) {
        this.opId = opId;
    }
    public Operations getNextOperation() {
        return this.nextOperation;
    }

    public void setNextOperation(Operations nextOperation) {
        this.nextOperation = nextOperation;
    }

    public Set getPrevOperation() {
        return this.prevOperation;
    }

    public void setPrevOperation(Set prevOperation) {
        this.prevOperation = prevOperation;
    }

    public String getOpName() {
        return this.opName;
    }
    
    public void setOpName(String opName) {
        this.opName = opName;
    }
    public String getOpDescription() {
        return this.opDescription;
    }
    
    public void setOpDescription(String opDescription) {
        this.opDescription = opDescription;
    }
    public Double getOpDuration() {
        return this.opDuration;
    }
    
    public void setOpDuration(Double opDuration) {
        this.opDuration = opDuration;
    }
    public String getOpComplexity() {
        return this.opComplexity;
    }
    
    public void setOpComplexity(String opComplexity) {
        this.opComplexity = opComplexity;
    }
    public String getOpComment() {
        return this.opComment;
    }
    
    public void setOpComment(String opComment) {
        this.opComment = opComment;
    }

    public Set getSuops() {
        return this.suops;
    }
    
    public void setSuops(Set suops) {
        this.suops = suops;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }

    public Set getDoops() {
        return this.doops;
    }
    
    public void setDoops(Set doops) {
        this.doops = doops;
    }
    public Set getEquipments() {
        return this.equipments;
    }
    
    public void setEquipments(Set equipments) {
        this.equipments = equipments;
    }
    public Set getCoops() {
        return this.coops;
    }
    
    public void setCoops(Set coops) {
        this.coops = coops;
    }

    public void trimStrings(){
       if (opName != null) opName = opName.trim();
       if (opDescription != null) opDescription = opDescription.trim();
       if (opComplexity != null) opComplexity = opComplexity.trim();
       if (opComment != null) opComment = opComment.trim();

    }

    public void cutNulls(){
       if (opName == null) opName = "-";
       if (opDescription == null) opDescription = "-";
       if (opComplexity == null) opComplexity = "-";
       if (opComment == null) opComment = "-";
       if (opDuration == null) opDuration = new Double(0);
    }




}


