package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Long prId;
     private String prPassport;
     private String prComment;
     private Date prDate;
     private String prGoden;
     private Set logs = new HashSet(0);

    public Products() {
    }

    public Products(String prPassport, String prComment, Date prDate, String prGoden, Set logs) {
       this.prPassport = prPassport;
       this.prComment = prComment;
       this.prDate = prDate;
       this.prGoden = prGoden;
       this.logs = logs;
    }
   
    public Long getPrId() {
        return this.prId;
    }
    
    public void setPrId(Long prId) {
        this.prId = prId;
    }
    public String getPrPassport() {
        return this.prPassport;
    }
    
    public void setPrPassport(String prPassport) {
        this.prPassport = prPassport;
    }
    public String getPrComment() {
        return this.prComment;
    }
    
    public void setPrComment(String prComment) {
        this.prComment = prComment;
    }
    public Date getPrDate() {
        return this.prDate;
    }
    
    public void setPrDate(Date prDate) {
        this.prDate = prDate;
    }
    public String getPrGoden() {
        return this.prGoden;
    }
    
    public void setPrGoden(String prGoden) {
        this.prGoden = prGoden;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }




}


