package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA

import com.mikevostrikov.ralter.app.domain.model.workers.Role;



/**
 * Rowe generated by hbm2java
 */
public class Rowe  implements java.io.Serializable {


     private Long roweId;
     private Webres webres;
     private Role roles;

    public Rowe() {
    }

	
    public Rowe(Long roweId) {
        this.roweId = roweId;
    }
    public Rowe(Long roweId, Webres webres, Role roles) {
       this.roweId = roweId;
       this.webres = webres;
       this.roles = roles;
    }
   
    public Long getRoweId() {
        return this.roweId;
    }
    
    public void setRoweId(Long roweId) {
        this.roweId = roweId;
    }
    public Webres getWebres() {
        return this.webres;
    }
    
    public void setWebres(Webres webres) {
        this.webres = webres;
    }
    public Role getRoles() {
        return this.roles;
    }
    
    public void setRoles(Role roles) {
        this.roles = roles;
    }




}


