package todo.com.mikevostrikov.ralter.app.domain.model;
// Generated 28.03.2009 2:16:48 by Hibernate Tools 3.2.1.GA


import com.mikevostrikov.ralter.web.controller.todo.ActionController;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Webres generated by hbm2java
 */
public class Webres implements java.io.Serializable {


    private Long weId;
    private String weName;
    private String weLocation;
    private String weServName;
    private Set rowes = new HashSet(0);
    transient private ActionController controller;

    public ActionController getController() {
        return controller;
    }
   
    public Long getWeId() {
        return this.weId;
    }
    
    public void setWeId(Long weId) {
        this.weId = weId;
        Arrays.asList(ActionController.values())
                .stream()
                .filter(sc -> sc.getId() == weId)
                .findFirst()
                .ifPresent(sc -> {
                    weName = sc.getDisplayName();
                    weServName = sc.name();
                    weLocation = sc.getUri();
                    controller = sc;
                });
    }
    public String getWeName() {
        return this.weName;
    }

    public void setWeName(String weName) {
        this.weName = weName;
    }

    public String getWeServName() {
        return this.weServName;
    }

    public void setWeServName(String weServName) {
        this.weServName = weServName;
    }

    public String getWeLocation() {
        return this.weLocation;
    }
    
    public void setWeLocation(String weLocation) {
        this.weLocation = weLocation;
    }
    public Set getRowes() {
        return this.rowes;
    }
    
    public void setRowes(Set rowes) {
        this.rowes = rowes;
    }

    public void trimStrings(){
       if (weName != null) weName = weName.trim();
       if (weLocation != null) weLocation = weLocation.trim();
       if (weServName != null) weServName = weServName.trim();
    }

    public void cutNulls(){
       if (weName == null) weName = "-";
       if (weLocation == null) weLocation = "-";
       if (weServName == null) weServName = "-";
    }


}
